title: "Опавшие листья"
description: >
  О программировании, науке и не только.

email: re.vkolesnikov@gmail.com
name: 'Василий Колесников'
author: 'Василий Колесников'
author_image: "/assets/images/author.jpg"

url: 'https://v-kolesnikov.github.io'
baseurl: "/blog"

logo: "/assets/images/logo.jpg"
cover: "/assets/images/cover.jpg"

paginate:	5

twitter_handle: '@re_vkolesnikov'
disqus: 'fallenleavesblog'
google_analytics: UA-74873357-1

social:
  - icon: twitter
    url: https://twitter.com/re_vkolesnikov
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon: github
    url: https://github.com/v-kolesnikov
    desc: Fork me on github

gems:
  - jemoji
  - jekyll-paginate
